// Otomatik oluşturuldu: tüm 135 fotoğraf + 35 video, kategoriye göre gruplu.

import type { GalleryImage } from "./content";

export const allPhotosByCategory: Record<string, GalleryImage[]> = {
  "exterior": [
    { src: "/images/exterior/exterior-01.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-02.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-03.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-04.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-05.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-06.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-07.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-08.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-09.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-10.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-11.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-12.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-13.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-14.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-15.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-16.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-17.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-18.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-19.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-20.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-21.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-22.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-23.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-24.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-25.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-26.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-27.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-28.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-29.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-30.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-31.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-32.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-33.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-34.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-35.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-36.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-37.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-38.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-39.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
    { src: "/images/exterior/exterior-40.webp", alt: "Sima Bungalov modern A-frame dış cephe" },
  ],
  "garden": [
    { src: "/images/garden/garden-01.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-02.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-03.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-04.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-05.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-06.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-07.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-08.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-09.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-10.webp", alt: "Sima Bungalov özel bahçe alanı" },
    { src: "/images/garden/garden-11.webp", alt: "Sima Bungalov özel bahçe alanı" },
  ],
  "pool": [
    { src: "/images/pool/pool-01.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-02.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-03.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-04.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-05.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-06.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-07.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-08.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-09.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-10.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-11.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-12.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
    { src: "/images/pool/pool-13.webp", alt: "Sima Bungalov ısıtmalı özel havuz" },
  ],
  "living-room": [
    { src: "/images/living-room/living-room-01.webp", alt: "Sima Bungalov iç mekan oturma alanı" },
    { src: "/images/living-room/living-room-02.webp", alt: "Sima Bungalov iç mekan oturma alanı" },
    { src: "/images/living-room/living-room-03.webp", alt: "Sima Bungalov iç mekan oturma alanı" },
    { src: "/images/living-room/living-room-04.webp", alt: "Sima Bungalov iç mekan oturma alanı" },
    { src: "/images/living-room/living-room-05.webp", alt: "Sima Bungalov iç mekan oturma alanı" },
    { src: "/images/living-room/living-room-06.webp", alt: "Sima Bungalov iç mekan oturma alanı" },
    { src: "/images/living-room/living-room-07.webp", alt: "Sima Bungalov iç mekan oturma alanı" },
  ],
  "kitchen": [
    { src: "/images/kitchen/kitchen-01.webp", alt: "Sima Bungalov modern mutfak" },
    { src: "/images/kitchen/kitchen-02.webp", alt: "Sima Bungalov modern mutfak" },
    { src: "/images/kitchen/kitchen-03.webp", alt: "Sima Bungalov modern mutfak" },
    { src: "/images/kitchen/kitchen-04.webp", alt: "Sima Bungalov modern mutfak" },
  ],
  "drone": [
    { src: "/images/drone/drone-01.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-02.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-03.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-04.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-05.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-06.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-07.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-08.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-09.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-10.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-11.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-12.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-13.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-14.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
    { src: "/images/drone/drone-15.webp", alt: "Sima Bungalov Sapanca drone havadan görünüm" },
  ],
  "night": [
    { src: "/images/night/night-01.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-02.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-03.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-04.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-05.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-06.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-07.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-08.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-09.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-10.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-11.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-12.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-13.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-14.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-15.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-16.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-17.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-18.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-19.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-20.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-21.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-22.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-23.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-24.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-25.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-26.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-27.webp", alt: "Sima Bungalov gece aydınlatması" },
    { src: "/images/night/night-28.webp", alt: "Sima Bungalov gece aydınlatması" },
  ],
  "lifestyle": [
    { src: "/images/lifestyle/lifestyle-01.webp", alt: "Sima Bungalov yaşam tarzı anı" },
    { src: "/images/lifestyle/lifestyle-02.webp", alt: "Sima Bungalov yaşam tarzı anı" },
    { src: "/images/lifestyle/lifestyle-03.webp", alt: "Sima Bungalov yaşam tarzı anı" },
    { src: "/images/lifestyle/lifestyle-04.webp", alt: "Sima Bungalov yaşam tarzı anı" },
    { src: "/images/lifestyle/lifestyle-05.webp", alt: "Sima Bungalov yaşam tarzı anı" },
    { src: "/images/lifestyle/lifestyle-06.webp", alt: "Sima Bungalov yaşam tarzı anı" },
    { src: "/images/lifestyle/lifestyle-07.webp", alt: "Sima Bungalov yaşam tarzı anı" },
    { src: "/images/lifestyle/lifestyle-08.webp", alt: "Sima Bungalov yaşam tarzı anı" },
  ],
  "bedroom": [
    { src: "/images/bedroom/bedroom-01.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-02.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-03.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-04.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-05.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-06.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-07.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-08.webp", alt: "Sima Bungalov yatak odası" },
    { src: "/images/bedroom/bedroom-09.webp", alt: "Sima Bungalov yatak odası" },
  ],
};

export interface VideoItem { src: string; poster: string; }

export const allVideosByCategory: Record<string, VideoItem[]> = {
  "videos-hero": [
    { src: "/video/gallery/videos-hero-01.mp4", poster: "/images/video-posters/videos-hero-01.webp" },
    { src: "/video/gallery/videos-hero-02.mp4", poster: "/images/video-posters/videos-hero-02.webp" },
    { src: "/video/gallery/videos-hero-03.mp4", poster: "/images/video-posters/videos-hero-03.webp" },
    { src: "/video/gallery/videos-hero-04.mp4", poster: "/images/video-posters/videos-hero-04.webp" },
    { src: "/video/gallery/videos-hero-05.mp4", poster: "/images/video-posters/videos-hero-05.webp" },
    { src: "/video/gallery/videos-hero-06.mp4", poster: "/images/video-posters/videos-hero-06.webp" },
    { src: "/video/gallery/videos-hero-07.mp4", poster: "/images/video-posters/videos-hero-07.webp" },
    { src: "/video/gallery/videos-hero-08.mp4", poster: "/images/video-posters/videos-hero-08.webp" },
    { src: "/video/gallery/videos-hero-09.mp4", poster: "/images/video-posters/videos-hero-09.webp" },
    { src: "/video/gallery/videos-hero-10.mp4", poster: "/images/video-posters/videos-hero-10.webp" },
    { src: "/video/gallery/videos-hero-11.mp4", poster: "/images/video-posters/videos-hero-11.webp" },
    { src: "/video/gallery/videos-hero-12.mp4", poster: "/images/video-posters/videos-hero-12.webp" },
    { src: "/video/gallery/videos-hero-13.mp4", poster: "/images/video-posters/videos-hero-13.webp" },
    { src: "/video/gallery/videos-hero-14.mp4", poster: "/images/video-posters/videos-hero-14.webp" },
    { src: "/video/gallery/videos-hero-15.mp4", poster: "/images/video-posters/videos-hero-15.webp" },
  ],
  "videos-pool-garden": [
    { src: "/video/gallery/videos-pool-garden-01.mp4", poster: "/images/video-posters/videos-pool-garden-01.webp" },
    { src: "/video/gallery/videos-pool-garden-02.mp4", poster: "/images/video-posters/videos-pool-garden-02.webp" },
    { src: "/video/gallery/videos-pool-garden-03.mp4", poster: "/images/video-posters/videos-pool-garden-03.webp" },
    { src: "/video/gallery/videos-pool-garden-04.mp4", poster: "/images/video-posters/videos-pool-garden-04.webp" },
    { src: "/video/gallery/videos-pool-garden-05.mp4", poster: "/images/video-posters/videos-pool-garden-05.webp" },
    { src: "/video/gallery/videos-pool-garden-06.mp4", poster: "/images/video-posters/videos-pool-garden-06.webp" },
    { src: "/video/gallery/videos-pool-garden-07.mp4", poster: "/images/video-posters/videos-pool-garden-07.webp" },
    { src: "/video/gallery/videos-pool-garden-08.mp4", poster: "/images/video-posters/videos-pool-garden-08.webp" },
    { src: "/video/gallery/videos-pool-garden-09.mp4", poster: "/images/video-posters/videos-pool-garden-09.webp" },
    { src: "/video/gallery/videos-pool-garden-10.mp4", poster: "/images/video-posters/videos-pool-garden-10.webp" },
    { src: "/video/gallery/videos-pool-garden-11.mp4", poster: "/images/video-posters/videos-pool-garden-11.webp" },
    { src: "/video/gallery/videos-pool-garden-12.mp4", poster: "/images/video-posters/videos-pool-garden-12.webp" },
    { src: "/video/gallery/videos-pool-garden-13.mp4", poster: "/images/video-posters/videos-pool-garden-13.webp" },
    { src: "/video/gallery/videos-pool-garden-14.mp4", poster: "/images/video-posters/videos-pool-garden-14.webp" },
    { src: "/video/gallery/videos-pool-garden-15.mp4", poster: "/images/video-posters/videos-pool-garden-15.webp" },
    { src: "/video/gallery/videos-pool-garden-16.mp4", poster: "/images/video-posters/videos-pool-garden-16.webp" },
    { src: "/video/gallery/videos-pool-garden-17.mp4", poster: "/images/video-posters/videos-pool-garden-17.webp" },
    { src: "/video/gallery/videos-pool-garden-18.mp4", poster: "/images/video-posters/videos-pool-garden-18.webp" },
  ],
  "videos-interior": [
    { src: "/video/gallery/videos-interior-01.mp4", poster: "/images/video-posters/videos-interior-01.webp" },
    { src: "/video/gallery/videos-interior-02.mp4", poster: "/images/video-posters/videos-interior-02.webp" },
  ],
};